# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CMPE188-HW0',
                'doc_host': 'https://Jin4202.github.io',
                'git_url': 'https://github.com/Jin4202/CMPE188-HW0',
                'lib_path': 'CMPE188_HW0'},
  'syms': {'CMPE188_HW0.core': {'CMPE188_HW0.core.foo': ('core.html#foo', 'CMPE188_HW0/core.py')}}}
